# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Cartoonist.destroy_all
# Publisher.destroy_all

cartoonist_data = [
"青山剛昌",
"阿賀沢紅茶",
"赤石路代",
"赤坂アカ",
"芥見下々",
"朝基まさし",
"あだち充",
"アベツカサ",
"天野明",
"絢薔子",
"荒川弘",
"荒木飛呂彦",
"安西信之",
"安野モヨコ",
"池田理代子",
"諫山創",
"一条ゆかり",
"樹なつみ",
"井上雄彦",
"臼井儀人",
"羽海野チカ",
"楳図かずお",
"浦沢直樹",
"遠藤達哉",
"尾田栄一郎",
"小畑健",
"小畑友紀",
"梶本あかり",
"神尾 葉子",
"狩谷成",
"河下水希",
"川原泉",
"岸本斉史",
"草凪みずほ",
"久保帯人",
"CLAMP",
"高坂 りと",
"吾峠呼世晴",
"小西幹久",
"小山宙哉",
"紺吉",
"桜井海",
"さくらももこ",
"佐々木尚",
"佐々木倫子",
"さとうふみや",
"椎名軽穂",
"篠原千絵",
"島袋光年",
"静脈",
"新沢基栄",
"せかねこ",
"空知英秋",
"高橋留美子",
"高屋奈月",
"武内直子",
"田島青",
"田辺イエロウ",
"多貫カヲ",
"種村有菜",
"田村由美",
"椿いづみ",
"紡木たく",
"手塚治虫",
"冨樫義博",
"殿ヶ谷美由記",
"鳥山明",
"中村光",
"那多ここね",
"西森博之",
"二ノ宮知子",
"野田サトル",
"原哲夫",
"東村アキコ",
"福本伸行",
"藤子・F・不二雄",
"藤子不二雄",
"藤田和日郎",
"藤本タツキ",
"塀内夏子",
"北条司",
"堀越耕平",
"ましろ",
"マツダミノル",
"美内すずえ",
"三香見サカ",
"水木しげる",
"水島新司",
"森本梢子",
"矢沢あい",
"矢吹健太朗",
"山田鐘人",
"大和和紀",
"やまもり三香",
"ゆでたまご",
"横槍メンゴ",
"吉住渉",
"吉田秋生",
"依田瑞稀",
"和久井健",
"その他"
]

cartoonist_data.each do |artist_name|
  Cartoonist.create!(artist_name: artist_name)
end

publishers = [
  { company_name: "講談社" },
  { company_name: "小学館" },
  { company_name: "集英社" },
  { company_name: "KADOKAWA" },
  { company_name: "秋田書店" },
  { company_name: "双葉社" },
  { company_name: "日本文芸社" },
  { company_name: "一迅社" },
  { company_name: "海王社" },
  { company_name: "白泉社" },
  { company_name: "徳間書店（Chara）" },
  { company_name: "竹書房" },
  { company_name: "新書館" },
  { company_name: "芳文社" },
  { company_name: "リブレ" },
  { company_name: "幻冬舎コミックス" },
  { company_name: "祥伝社" },
  { company_name: "少年画報社" },
  { company_name: "マッグガーデン" },
  { company_name: "オーバーラップ" },
  { company_name: "シュークリームPOP" },
  { company_name: "新潮社" },
  { company_name: "スクウェア・エニックス" },
  { company_name: "その他" }
]

publishers.each do |publisher|
  Publisher.create!(publisher)
end